CommentFix
tiiuae/ghaf pull request #13
Opened 2022-12-21 09:57 UTC by alextserepov

- adding short text on YubiHSM usage

Signed-off-by: Aleksandr Tserepov-Savolainen <alextserepov@gmail.com>

2022-12-21 09:59 UTC, alextserepov commented
As per: https://github.com/tiiuae/ghaf/pull/6#discussion_r1048444733 
Will also add more text on general HSM and YubiHSM usage in a separate PR.

2022-12-21 14:33 UTC, jenninikko requested changes
@alextserepov small changes are requested.

2022-12-21 14:33 UTC, jenninikko commented on src/scs/pki.md
> +On-premises solution can be further improved by adding a Hardware Security Module (HSM), which is a physical device for managing cryptographic material, e.g. digital keys. HSM can be also used to per
On-premises solution can be further improved by adding a Hardware Security Module (HSM)**.** It is a physical device for managing cryptographic material such as digital keys.
(new line)
HSM can be also used to perform cryptographic operations such as digital signing, encryption **,** and decryption. HSM contains one or more Secure Cryptoprocessor**s** that are dedicated microprocessor**s** optimized for carrying out cryptographic operations.
(new line)
One example of affordable HSM solutions is YubiHSM developed by Yubico.

2022-12-22 13:52 UTC, jenninikko approved these changes

2022-12-22 13:52 UTC, merged