Add initial defensive networking VM called IDS-VM
tiiuae/ghaf pull request #146
Opened 2023-05-23 13:01 UTC by riskuuse

This PR adds a new VM to act as a skeleton for further development.
It's first feature is the interactive proxy (mitmproxy).

The networking layout proposal is updated to documentation. More technically it is depicted in this diagram. 
![IDS-VM](https://github.com/tiiuae/ghaf/assets/51403673/8e3e4af0-2a14-4262-9c88-757b20a06ae7)

- DHCP server is moved away from netvm into this one.
- Host will have ssh access for debugging purposes via dedicated IP address.
- To be able to fully test this, VM with browser is required.

A quick way of testing functionality:
1. Before building, set WiFi credentials of your target (tested with nvidia-jetson-orin.nix)
2. Build, flash and boot.
3. Open host terminal and type.
     `[ghaf@ghaf-host:~]$ sudo route add default gw 192.168.111.1 virbr1`
4. Unplug ethernet cable if you want to be extra certain that WiFi is used for network connection.
5. Ssh to IDSvm:
    `[ghaf@ghaf-host:~]$ ssh ghaf@192.168.111.1`
6. On IDSvm run:
    `[ghaf@idsvm:~]$ sudo iptables -t nat -A PREROUTING -i ethint1 -p tcp --dport 80 -j REDIRECT --to-port 8080`
    `[ghaf@idsvm:~]$ sudo iptables -t nat -A PREROUTING -i ethint1 -p tcp --dport 443 -j REDIRECT --to-port 8080`
7. Open Chromium browser and verify that you can't connect to any site.
8. On IDSvm run:
    `[ghaf@idsvm:~]$ mitmproxy --mode transparent --set confdir=/etc/mitmproxy`
9. With Chromium browse to address mitm.it
    - Download mitmproxy-ca-cert.pem
    - Install it to browser: Settings -> Privacy and Security -> Security -> Manage certificates -> Authorities -> Import -> open downloaded file -> tick box "Trust this certificate for identifying websites" -> Ok
10. Start browsing and see some action on mitmproxy TUI.

To test on target generic-x86_64-debug:
The same procedure as above, except at step 1 it is required to set IDs and path of your wireless network controller to
generic-x86_64.nix. May the command `lspci -nn` be your friend. Pay also attention to the part that says _cheat hack_.

2023-05-24 05:15 UTC, brianmcgillion commented
@jenninikko Can we move that diagram into the Ghaf documentation?

2023-05-24 13:57 UTC, jenninikko commented
> @jenninikko Can we move that diagram into the Ghaf documentation?

As this is the draft pull request, we decided to update an existing image and wait for feedback first.

2023-05-24 14:14 UTC, vilvo commented on docs/src/img/netvm.drawio.png
Thanks! Awesome to update the existing netvm ADR diagram to outline the change in VM composition.

2023-05-24 14:28 UTC, vilvo commented on docs/src/img/netvm.drawio.png
We will have to clarify the roles between `netvm` and the introduced `ids-vm` further.
For example:

`netvm` must have the default firewall rules on external facing NIC and the network is bridged to only `ids-vm`. `netvm` has minimal kernel with the passthrough NIC native device driver built-in. `netvm` (in release-target) has minimal read-only filesystem with no user space tools - so minimal that the `netvm` can be loaded to RAM upon VM start. If there's any other seen tasks for `netvm`, please comment. My point is that even when this VM should be super minimal with specific task, it will come with some overhead from host context switching for the I/O between the guests. 

`ids-vm` serves system defensive role and host system internal network services (dhcpd, ntpd, reverse proxying for p2p, etc.) and intrusion detection systems (IDS) such as deep packet inspection (DPI), interactive proxy (mitm analysis), system internal firewall (network address translation, etc.)

2023-05-24 14:33 UTC, vilvo commented on docs/src/img/netvm.drawio.png
Optionally we could call the `idsvm` as `ztvm` for zero trust. This could be the place for the zero trust policy engine and policy administration. Policies could be then enforced into the netvm firewall and connections (even `established`). @brianmcgillion ?

2023-05-24 14:38 UTC, vilvo commented on docs/src/img/netvm.drawio.png
Reviewing beyond above comments - I leave it building and updating to Orin AGX to analyze it a bit further but in general - the declarations look like what it says in the diagram - an additional guest VM skeleton with specific task, bridged from netvm. Good first phase implementation.

2023-05-25 08:04 UTC, vilvo commented
The basic network setup - debug access to guests from host - verified to work via debug serial to host:
```
[ghaf@ghaf-host:~]$ ssh 192.168.110.1
The authenticity of host '192.168.110.1 (192.168.110.1)' can't be established.
ED25519 key fingerprint is SHA256:Uv/eznildVhMis1hQEc3JqRi0jrsMaZCBwAcrGhFxmk.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.110.1' (ED25519) to the list of known hosts.
(ghaf@192.168.110.1) Password:

[ghaf@netvm:~]$ ifconfig
ethint0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.1  netmask 255.255.255.0  broadcast 192.168.100.255
        inet6 fe80::ff:fe01:101  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:01:01:01  txqueuelen 1000  (Ethernet)
        RX packets 255  bytes 24428 (23.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 128  bytes 16063 (15.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 152  bytes 11944 (11.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 152  bytes 11944 (11.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp0s5f0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b4:8c:9d:1c:47:8f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


[ghaf@netvm:~]$
logout
Connection to 192.168.110.1 closed.

[ghaf@ghaf-host:~]$ ssh 192.168.110.3
The authenticity of host '192.168.110.3 (192.168.110.3)' can't be established.
ED25519 key fingerprint is SHA256:EuoDFDIcZ8tJzvneaFl9RH0Kf4ZyMrNOxkQuHdPxLKk.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.110.3' (ED25519) to the list of known hosts.
(ghaf@192.168.110.3) Password:

[ghaf@idsvm:~]$ ifconfig
ethint0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.2  netmask 255.255.255.0  broadcast 192.168.100.255
        inet6 fe80::ff:fe01:102  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:01:01:02  txqueuelen 1000  (Ethernet)
        RX packets 158  bytes 18541 (18.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 276  bytes 26007 (25.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ethint1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.101.1  netmask 255.255.255.0  broadcast 192.168.101.255
        inet6 fe80::ff:fe01:202  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:01:02:02  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21  bytes 1624 (1.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 262  bytes 20918 (20.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 262  bytes 20918 (20.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


[ghaf@idsvm:~]$
``` 
Also the debug ethernet directly to host works after connecting the ethernet cable (dhcp):
```
[ghaf@ghaf-host:~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.8.208  netmask 255.255.255.0  broadcast 172.18.8.255
        inet6 fe80::4ab0:2dff:fedd:cff1  prefixlen 64  scopeid 0x20<link>
        ether 48:b0:2d:dd:cf:f1  txqueuelen 1000  (Ethernet)
        RX packets 501  bytes 122391 (119.5 KiB)
        RX errors 0  dropped 34  overruns 0  frame 0
        TX packets 439  bytes 47449 (46.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

What does not work:
- name resolution (DNS) from host without changing the `/etc/resolv.conf` nameserver to valid DNS
- `idsvm` is read-only so it is not possible to install a browser, like elinks with `nix-shell -p elinks`. So it's unclear how the mitmproxy was tested with browser from within the `idsvm`. I can get the mitmproxy running though inside the `idsvm` though. This testing procedure to enjoy the magic is better described in more detail instead of https://github.com/tiiuae/ghaf/pull/146/files#diff-1baa61e1246e8921d63ad51b7a7f0e1e925cf8966c8bad628f5e9d7478c7522cR23 - I've seen the mitm demo but I'm not familiar with the demo setup procedures - it's probably the same for anyone else.

2023-05-25 08:06 UTC, vilvo requested changes
Please add more detailed notes to test the mitmproxy. I'm guessing the outbound browser access for the chromium on the host might work if wifi passthrough (if configured on netvm) is used instead of host debug access ethernet.

2023-05-25 08:31 UTC, vilvo commented
I tried to enable only the wifi passthrough for external NIC via netvm as follows:
1. set proper wifi secrets to https://github.com/tiiuae/ghaf/blob/main/targets/nvidia-jetson-orin.nix#L59
2. `nixos-rebuild --flake .#nvidia-jetson-orin-debug --target-host root@ghaf-host --fast switch` 
3. disconnect host ethernet cable
4. login to host over debug serial
5. login to `netvm` from host over ssh
5a. check if the `wlp0s5f0` in `netvm` got an ip address - FAIL
6. reboot the whole hardware
6a. repeat steps 3.-5.
6b. check if the `wlp0s5f0` in `netvm` got an ip address - FAIL

Can't install anything to guests in debug mode due to read-only filesystem.

2023-06-01 08:50 UTC, riskuuse commented
> Please add more detailed notes to test the mitmproxy. I'm guessing the outbound browser access for the chromium on the host might work if wifi passthrough (if configured on netvm) is used instead of host debug access ethernet.

More detailed testing instructions are now added to description.

2024-02-28 14:13 UTC, closed without merging

2024-02-28 14:16 UTC, riskuuse commented
This PR is replaced by PR #422 and thus closed.