docs: Add Ghaf security fix automation section
tiiuae/ghaf pull request #186
Opened 2023-06-21 11:50 UTC by henrirosten

Under SCS documentation, add a section for security fix automation.

2023-06-21 12:37 UTC, jenninikko commented
Let's return to this when GitHub Pages documentation is running again.

2023-06-22 08:12 UTC, alextserepov approved these changes
Looking Good!

2023-06-22 08:56 UTC, brianmcgillion approved these changes
Looks good to me !

2023-06-26 06:16 UTC, henrirosten commented
> _We use diagrams.net for drawings: https://github.com/tiiuae/ghaf/blob/main/docs/README-docs.md#adding-new-files. Would you mind if I will redraw this docs/src/img/ghaf-security-fix-automation.uxf after the merge?_

Sure, that's fine. In general, my suggestion would be to use a tool that allows you to export the editable image format and include the editable image to the version control, so that it's possible to later modify the image. I'd also suggest to use svg or other vector image format in the documentation so that you would not have to include raster images to the git repo.


> _What do you think of using "Security Automation" instead of "Security Fix Automation"? Or maybe I am wrong and it is a different process?_

Term "Security" alone implies more that what is described on the documentation added by this PR. To me, the term "Security Automation" therefore sounds too generic; we are not claiming we try to automate everything that is part of "Security".

"Security Fix" might also not be the best term, but I couldn't come up with anything better. "Security Patch Automation" to me implies the process would only include patching, where, in fact many of the security fixes will be version updates not patches. I settled with the term "fix", since I think it includes both type of fixes: patches and version updates.

2023-06-26 13:44 UTC, jenninikko commented
> Sure, that's fine. In general, my suggestion would be to use a tool that allows you to export the editable image format and include the editable image to the version control, so that it's possible to later modify the image. I'd also suggest to use svg or other vector image format in the documentation so that you would not have to include raster images to the git repo.

We use diagrams.net because there is a feature not only to create but also to edit the diagrams: Editable Bitmap Image format (.png) or Editable Bitmap Image format (.svg). Both are with embedded XML.

Currently, in the repository, there are only PNG files but I do not mind to change it. Moreover, I did not think about it before, just used the first option with PNG, as I remember that not all web tools like to work with SVG :D But I really like the idea that SVG's file size is smaller. I will change and test it with the next iteration.

And about this one:

> Term "Security" alone implies more than what is described on the documentation added by this PR. To me, the term "Security Automation" therefore sounds too generic; we are not claiming we try to automate everything that is part of "Security".

> "Security Fix" might also not be the best term, but I couldn't come up with anything better. "Security Patch Automation" to me implies the process would only include patching, where, in fact many of the security fixes will be version updates not patches. I settled with the term "fix", since I think it includes both type of fixes: patches and version updates.

You are right that Security Automation is more of a general process. Maybe something like Fix-Based Security Automation? Anyway, it does not affect the merge process, we can discuss it separately.

2023-08-02 11:45 UTC, jenninikko requested changes
Thanks for your pull request. Some minor comments can be found below.

In addition to the comments, please replace the image (I sent it to you in email), and also update the SUMMARY.md in the following way:

instead of this
```
- [Supply Chain Security](scs/scs.md)
    - [SLSA Framework](scs/slsa-framework.md)
    - [Basic Security Measures](scs/basics.md)
    - [Software Bill of Materials](scs/sbom.md)
    - [Public Key Infrastructure](scs/pki.md)
    - [Patch Management Automation](scs/patching-automation.md)
```
you should have
```
- [Supply Chain Security](scs/scs.md)
    - [SLSA Framework](scs/slsa-framework.md)
    - [Basic Security Measures](scs/basics.md)
    - [Software Bill of Materials](scs/sbom.md)
    - [Public Key Infrastructure](scs/pki.md)
    - [NAME OF YOUR SECTION](scs/ghaf-security-fix-automation.md)
```

The most important thing is to decide which section title to use.

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/ghaf-security-fix-automation.md
> +  **(2)** Run automated vulnerability analysis tooling for each relevant Ghaf build target. For Ghaf, being Nix-based, we propose to use [nix_secupdates](https://github.com/tiiuae/sbomnix/tree/main/s
an auto triaged vulnerability report -> an **auto-triaged** vulnerability report

Delete this sentence:
For more details on the nix_secupdates, refer the [relevant documentation on nix_secupdates repository](https://github.com/tiiuae/sbomnix/tree/main/scripts/nixupdate#nix_secupdates).

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/ghaf-security-fix-automation.md
> +- **Manual vulnerability analysis** is a manual process, which is also executed on daily basis.<br />
on daily basis -> on **a** daily basis

Put a colon at the end of the sentence instead of a period.

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/ghaf-security-fix-automation.md
> +  **(3)** Using the auto triaged vulnerability report from the previous step, manually analyze the automation results comparing the new results to earlier day's results from the relevant build. <br /
the auto triaged vulnerability report -> the **auto-triaged** vulnerability report

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/ghaf-security-fix-automation.md
> +  **(4)** If there are any fixed issues compared to the last analyzed report, initiate the Ghaf flake lockfile update for relevant inputs to include the vulnerability fixes from nixpkgs upstream to r
lockfile -- decide together

from nixpkgs upstream -> from **the** nixpkgs upstream

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/ghaf-security-fix-automation.md
> +  **(5)** If there are any new vulnerabilities compared to the last analyzed report, manually analyze each vulnerability in detail. If the issue requires a fix, push a fix PR to relevant nixpkgs bran
push a fix PR to relevant nixpkgs branches -> **create a pull request to push the changes** to relevant nixpkgs branches

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/ghaf-security-fix-automation.md
> +The process described above is an upstream-first, with the main benefit of eliminating the need to maintain our own vulnerability fix patches on top of nixpgks in Ghaf. This process will also benefit
No commas are needed in both sentences.

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/sbom.md
> +Ghaf is based on Nix, therefore, the selected SBOM tooling needs to support creating SBOMs for nix artifacts. As part of the Ghaf project, we have created the sbomnix tool to support SBOM generation
for any nix targets -> for any **Nix-based** targets

2023-08-02 11:45 UTC, jenninikko commented on docs/src/scs/scs.md
> +- [Ghaf Security Fix Automation](../scs/ghaf-security-fix-automation.md)
Fix-Based Security Automation?

2023-08-07 08:02 UTC, henrirosten commented on docs/src/scs/ghaf-security-fix-automation.md
> +# Ghaf Security Fix Automation
I think "Ghaf Security Fix Automation" better capture the idea, as I explained earlier.
Unless you block the PR on this, let's keep it like it is.

2023-08-07 08:03 UTC, henrirosten commented on docs/src/scs/scs.md
> +- [Ghaf Security Fix Automation](../scs/ghaf-security-fix-automation.md)
See: https://github.com/tiiuae/ghaf/pull/186#discussion_r1285520626

2023-08-07 08:07 UTC, henrirosten commented
> instead of this
> 
> ```
> - [Supply Chain Security](scs/scs.md)
>     - [SLSA Framework](scs/slsa-framework.md)
>     - [Basic Security Measures](scs/basics.md)
>     - [Software Bill of Materials](scs/sbom.md)
>     - [Public Key Infrastructure](scs/pki.md)
>     - [Patch Management Automation](scs/patching-automation.md)
> ```
> 
> you should have
> 
> ```
> - [Supply Chain Security](scs/scs.md)
>     - [SLSA Framework](scs/slsa-framework.md)
>     - [Basic Security Measures](scs/basics.md)
>     - [Software Bill of Materials](scs/sbom.md)
>     - [Public Key Infrastructure](scs/pki.md)
>     - [NAME OF YOUR SECTION](scs/ghaf-security-fix-automation.md)
> ```

Do you mean you want to remove the "[Patch Management Automation](scs/patching-automation.md)" section altogether? 
For the name of the new section, I think "Ghaf Security Fix Automation" best describes what we are attempting to do.

2023-08-22 08:15 UTC, jenninikko approved these changes

2023-08-22 08:15 UTC, merged