Add windows launcher for x86_64
tiiuae/ghaf pull request #212
Opened 2023-07-04 15:01 UTC by nesteroff

This pull request adds windows launcher to generic x86_64 image. It can be launched with either an ISO image or QCOW2:
`Usage: windows-launcher ./Win11_22H2_English_x64v2.iso or ./win11.qcow2`

When the script launched with an ISO image it creates an empty QCOW2 image in the same directory which is used as a system disk in the VM. After Windows 11 has been installed the script should be launched with the QCOW2 image.

How to run Windows 11 VM:
- Download Windows 11 ISO from [https://www.microsoft.com/software-download/windows11](https://www.microsoft.com/software-download/windows11)
- Run `windows launcher ./Win11_22H2_English_x64v2.iso` and hit any key to boot from the ISO.
- In order to bypass Windows 11 system requirement hit `Shift+F10` to open a command prompt and type `regedit`. In `HKEY_LOCAL_MACHINE\SYSTEM\Setup` create a new `LabConfig` key (with right click select New, Key, type LabConfig). In this key create a DWORD (32-bit) parameter with the name `BypassTPMCheck` and value 1. Also create a similar value with the `BypassSecureBootCheck` name.
- Install Windows 11 in the virtual machine.
- When it asks to connect to a network hit Shift+F10 to open up a command prompt and type oobe\bypassnro. It will restart configuration and next time there will be a new button “I don’t have internet“. Hit that button to skip connecting to network and continue the installation.
- After the installation is completed the script should be launched with the QCOW2 image: `windows-launcher ./win11.qcow2`

2023-07-05 18:20 UTC, mikatammi approved these changes
Generally looks good to me, however I didn't test building these changes

2023-07-05 20:17 UTC, nesteroff commented
Thanks. I've tested on x86 and tomorrow I'm going to test it on Nvidia to make sure it still works there.

2023-07-06 13:07 UTC, brianmcgillion approved these changes
This looks great!

2023-07-13 13:18 UTC, jenninikko requested changes
A few comments, as usual!

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +4. In order to bypass Windows 11 system requirement hit Shift+F10 to open a command prompt and type regedit. In `HKEY_LOCAL_MACHINE\SYSTEM\Setup` create a new `LabConfig` key (with right click select
Replace with:

3. In order to bypass Windows 11 system requirements, open cmd with Shift+F10 and type `regedit`. In HKEY_LOCAL_MACHINE\SYSTEM\Setup, right-click _New > Key_ and type _LabConfig_. For this key create two DWORD (32-bit) parameters:
    * Name: `BypassTPMCheck`, value `1`.
    * Name: `BypassSecureBootCheck`, value `1`.

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +    > **Warning:** when running Ghaf on a notebook it might be needed to press the Fn key with Shift+F10. Also sometimes when Shift+F10 is pressed the command window opens in the background and not v
Replace with:

`> TIP: [For Ghaf running on a laptop] If after pressing Shift+F10 the command window is not displayed, try again with the Fn key (Shift+Fn+F10) or switch between opened windows by using Alt+Tab.`

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +5. Install Windows 11 in the virtual machine.
in the VM

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +6. Windows 11 requires Internet access to finish the setup. To boot the VM without an Internet connection, open cmd with Shift+F10 and type `OOBE\BYPASSNRO`. It will restart configuration and next ti
Replace with this:

Windows 11 requires Internet access to finish the setup. To boot the VM without an Internet connection, open cmd with Shift+F10 and type `OOBE\BYPASSNRO`. After the configuration restart click “I don’t have internet“ to skip the Internet connection step and continue the installation.

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +7. After the installation is completed the script should be launched with the QCOW2 image:
the script **is** launched with

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +1. Instead of running windows-launcher from the command line it is possible to launch the Windows 11 VM by clicking the corresponding icon in the Weston taskbar.
Let's make this not a numbered list, but regular sentences: each one as a new line with a blank line between them.

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +1. It is possible to pass additional parameters to QEMU when running windows-launcher from the command line.
Let's make this not a numbered list, but regular sentences: each one as a new line with a blank line between them.

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +1. Instead of running windows-launcher from the command line it is possible to launch the Windows 11 VM by clicking the corresponding icon in the Weston taskbar.
Windows launcher

2023-07-13 13:18 UTC, jenninikko commented on docs/src/research/run_win_vm.md
> +1. It is possible to pass additional parameters to QEMU when running windows-launcher from the command line.
Windows launcher

2023-07-13 13:50 UTC, nesteroff commented
> A few comments, as usual!

Thanks! I've made those changes. Please have a look. Hopefully, I didn't screw it up.

2023-07-14 11:08 UTC, jenninikko approved these changes

2023-07-17 08:24 UTC, merged