Add some information on cross compilation
tiiuae/ghaf pull request #24
Opened 2023-01-04 07:51 UTC by brianmcgillion

Signed-off-by: Brian McGillion <brian.mcgillion@tii.ae>

2023-01-04 08:03 UTC, vilvo approved these changes
lgtm

2023-01-05 15:32 UTC, jenninikko commented on docs/src/build_config/cross_compilation.md
> +# Cross Compilation
Is this new section is going to be under the Build Configurations chapter?
Like this:
-- Build Configurations
-------Cross Compilation
If yes,  you need to update the SUMMARY.file as well. Some general instructions are here: https://github.com/tiiuae/ghaf/blob/main/docs/README.md#working-with-files.

2023-01-05 15:37 UTC, jenninikko commented on README.md
> +As there are some packages that are not cross-compilation aware you may set the following in you configuration.nix to enable binfmt.
As there are some packages that are not cross-compilation aware **,** you **can** set the following in you `configuration.nix` to enable binfmt.

2023-01-05 16:08 UTC, jenninikko requested changes
Hei Brian, this is a good one. Could not skip some commas and hyphens, and SUMMARY.md needs to be updated. I also keep forgetting about it all the time :)

2023-01-05 16:08 UTC, jenninikko commented on docs/src/build_config/cross_compilation.md
> +Ghaf is targeted at a range of devices and form factors that support different Instruction Set Architectures (ISA). Many small form-factor edge devices are not powerful enough to compile the needed a
...is ``x\_86`` **,** this...

2023-01-05 16:37 UTC, brianmcgillion commented on docs/src/build_config/cross_compilation.md
> +This will involve working with upstream package maintainers to ensure that the packages are cross compilation aware. This will be addressed on a package by package basis.
I only speak the language. what is an adjective let alone compound adjective :)

2023-01-05 17:43 UTC, jenninikko approved these changes

2023-01-05 17:43 UTC, merged