Enable secure boot for Ghaf Host.
tiiuae/ghaf pull request #388
Opened 2023-12-01 14:14 UTC by vunnyso

## Description of changes

This patch will enable secure boot feature on Lenovo X1 Carbon for Ghaf Host for debug builds.

## Checklist for things done

- [X] Summary of the proposed changes in the PR description
- [X] More detailed description in the commit message(s)
- [X] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [-] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [-] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [-] PR linked to architecture documentation and requirement(s) (ticket id)
- [X] Test procedure described (or includes tests). Select one or more:
  - [X] Tested on Lenovo X1 `x86_64`
  - [-] Tested on Jetson Orin NX or AGX `aarch64`
  - [-] Tested on Polarfire `riscv64`
- [X] Author has run `nix flake check --accept-flake-config --allow-import-from-derivation` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [X] Author has added reviewers and removed PR draft status

## Testing

https://github.com/tiiuae/ghaf/blob/main/docs/src/architecture/secureboot.md

2023-12-01 14:21 UTC, vilvo approved these changes

2023-12-01 15:06 UTC, brianmcgillion requested changes
absolutly not

2023-12-04 13:21 UTC, vunnyso commented
> absolutly not

Hi @brianmcgillion can you please share the reason why not?

2024-09-09 05:34 UTC, vunnyso commented
Secure boot is enabled in https://github.com/tiiuae/ghaf/pull/758 (.#lenovo-x1-extras-debug)
Hence closing this.

2024-09-09 05:34 UTC, closed without merging