Fix electron cross-build on recent nixpkgs
tiiuae/ghaf pull request #498
Opened 2024-03-06 12:17 UTC by avnik

## Description of changes

Fix chromium/electron cross-compilation via reverting https://github.com/NixOS/nixpkgs/commit/fcdea38355b817b86101b9bb6f717858bc96b4eb
This commit is "do nothing" on current ghaf, but fix problem with upcoming nixpkgs update (which have commit above).

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [x] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [x] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [x] Author has added reviewers and removed PR draft status

## Testing

Update nixpkgs input via `nix flake lock --update-input nixpkgs`, build.
(I personally checked on 14bc70677726d6d5989e6d5db6c4f618e70259ac, where problem was introduced)

2024-03-06 19:34 UTC, brianmcgillion approved these changes

2024-03-06 20:10 UTC, mikatammi commented
Testing against this + latest nixpkgs in progress for all platforms

2024-03-06 20:47 UTC, mikatammi requested changes
Does not seem to fix the issue :( electron build still fails with the same error (with the latest nixos-23.11 nixpkgs):
```
electron-unwrapped-aarch64-unknown-linux-gnu> FAILED: host/libffmpeg.so host/libffmpeg.so.TOC
electron-unwrapped-aarch64-unknown-linux-gnu> "python3" "../../build/toolchain/gcc_solink_wrapper.py" --readelf="$READELF_FOR_BUILD" --nm="$NM_FOR_BUILD"  --sofile="host/libffmpeg.so" --tocfile="host/libffmpeg.so.TOC" --output="host/libffmpeg.so" -- $CXX_FOR_BUILD -shared -Wl,-soname="libffmpeg.so" -Wl,-Bsymbolic -L host/gen/third_party/ffmpeg -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--icf=all -Wl,--color-diagnostics -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -m64 -no-canonical-prefixes -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-z,defs -Wl,--as-needed -nostdlib++ -Wl,-rpath=\$ORIGIN -o "host/libffmpeg.so" @"host/libffmpeg.so.rsp"
electron-unwrapped-aarch64-unknown-linux-gnu> ld.lld: error: /nix/store/6mg348c8x8nvfv1ad57my4px55wgl4ax-zlib-aarch64-unknown-linux-gnu-1.3/lib/libz.so is incompatible with elf64-x86-64
electron-unwrapped-aarch64-unknown-linux-gnu> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

2024-03-06 20:54 UTC, mikatammi commented
Also nixpkgs does not have commit with hash: 14bc70677726d6d5989e6d5db6c4f618e70259ac

2024-03-06 20:59 UTC, mikatammi commented
Just to check I'll do another build against `nixpkgs.url = "github:NixOS/nixpkgs/fcdea38355b817b86101b9bb6f717858bc96b4eb";`

2024-03-06 21:41 UTC, mikatammi commented
Github Runner seems to run out of disk space

2024-03-07 06:58 UTC, mikatammi requested changes
> Just to check I'll do another build against `nixpkgs.url = "github:NixOS/nixpkgs/fcdea38355b817b86101b9bb6f717858bc96b4eb";`

Does not work even with this :( electron-unwrapped build fails: ```
FAILED: host/libffmpeg.so host/libffmpeg.so.TOC
"python3" "../../build/toolchain/gcc_solink_wrapper.py" --readelf="$READELF_FOR_BUILD" --nm="$NM_FOR_BUILD"  --sofi>
ld.lld: error: /nix/store/ychmvpzwspj5grynwh1zyba8vfp9a1j7-zlib-aarch64-unknown-linux-gnu-1.3/lib/libz.so is incomp>
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

2024-03-07 07:45 UTC, mikatammi commented
Also the chromium itself fails with:
```
[51000/86742] LINK host/generate_colors_info
FAILED: host/generate_colors_info
"python3" "../../build/toolchain/gcc_link_wrapper.py" --output="host/generate_colors_info" -- $CXX_FOR_BUILD -fuse->
ld.lld: error: /nix/store/zlahca9p42v8rd9yxvj89341p56qlxz0-libpng-aarch64-unknown-linux-gnu-1.6.40/lib/libpng16.so >
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

2024-03-18 13:24 UTC, avnik commented
@mikatammi I looked into patch, no changes in buildprocess. No touching of makefiles, etc. Looks like it caused by shuffling of libraries or their symbold.

I'll check  build against against today's unstable or master if you like

2024-04-04 08:23 UTC, leivos-unikie commented
Tested native and cross-compiled flash-script for Orin AGX. They work fine.

I don't know if it relates to this PR but while testing I noticed that Element app can be launched. There is an old open bug about Element not launching at all on Orin. At least with this PR it launches but there is 30-40 sec delay between clicking the icon and app window appearing.

2024-04-04 09:13 UTC, merged

2024-04-04 09:58 UTC, mikatammi reviewed
Was about to say the tests go through now