Add SSH key to ghaf installer
tiiuae/ghaf pull request #530
Opened 2024-03-21 10:33 UTC by leivos-unikie

Add SSH key to ghaf installer in debug mode. This enables ci-test-automation to run the installer.

## Description of changes

## Checklist for things done

- [ ] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [ ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [ ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing

2024-03-27 12:13 UTC, leivos-unikie commented
@azbeleva, could you test this since you have the corresponding private key

2024-03-28 12:20 UTC, azbeleva approved these changes
works fine with autotests' private key

2024-04-03 08:44 UTC, vilvo requested changes
Functionally this works but I'm concerned about distributing the `-debug`-builds `authorizedKeys`-declarations to many places. Pre-configured public keys have been questioned - even in `-debug`-builds - for a reason but there's no good alternative as of now. 

I propose you move the test automation public key to https://github.com/tiiuae/ghaf/blob/main/modules/common/development/ssh.nix#L10 instead, import it here in the installer target for `-debug` builds and assign for  installer `nixos` user. That way we won't have those authorized public keys declared in multiple places. Note: please don't import the whole debug-profile - all of that is not needed in the installer `debug`-builds.

2024-04-08 13:06 UTC, brianmcgillion approved these changes

2024-04-08 13:06 UTC, merged