Doc: add Nvidia UART passthrough
tiiuae/ghaf pull request #54
Opened 2023-01-20 11:10 UTC by ruizjuanpablo

2023-01-24 10:00 UTC, jenninikko requested changes
@ruizjuanpablo, thanks for this great pull request! 
You can find my minor comments below.

2023-01-24 15:20 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +This document describes the UART passthrough implementations on the Nvidia AGX Orin
Maybe not, because there is no source code for UART passthrough, only the configuration described here.

2023-01-24 15:22 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +# Nvidia AGX Orin - UART Passthrough
Done

2023-01-24 15:22 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +## Start the Guest VM
Done

2023-01-24 15:27 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +This because the UARTI does not show any dependencies on its device tree as shown
Done

2023-01-24 15:28 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +bellow:
Done

2023-01-24 15:29 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +node in the tegra234-soc-uart.dtsi device tree file [^note1] as follow:
Done

2023-01-24 15:31 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +The guest device tree is based on the device tree extracted from Qemu virt machine.
Done

2023-01-24 15:31 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
> +To get the base Qemu device tree you can run the following command:
Done

2023-01-24 15:33 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/passthrough.md
> +Devices passthrough to virtual machines (VM) allow us to isolate the device drivers
Done

2023-01-24 15:34 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/passthrough.md
> +and its memory access in one or several VMs. This reduce the Trusted Code Base (TCB)
Done

2023-01-24 15:34 UTC, ruizjuanpablo commented on docs/src/build_config/passthrough/passthrough.md
> +in the host, due the passedthrough device drivers can be removed completely
Done

2023-01-24 15:40 UTC, ruizjuanpablo commented
Thanks for the very useful comments. I have fixed the documentation according to them.

2023-01-25 12:03 UTC, jenninikko commented
Thanks for updating! Vadim Likholetov also reviewed this pull request.

2023-01-25 12:04 UTC, merged