Initial AudioVM implementation with pipewire and pulseaudio
tiiuae/ghaf pull request #576
Opened 2024-04-24 05:50 UTC by josa41

Initial version of AudioVM with Pipewire backend and pulseaudio TCP remote communication layer for the guest VMs. Note that this is not really secure design (yet) basically all VMs can access the pulseaudio TCP service.

## Description of changes

Separate AudioVM with HW passthrough audio device
- Pipewire backend with pulseaudio tunnel for VM client

## Checklist for things done

- [X ] Summary of the proposed changes in the PR description
- [X ] More detailed description in the commit message(s)
- [X ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [X ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [X ] Test procedure described (or includes tests). Select one or more:
  - [X ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [X ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing
- 3.5mm headset works
- Integrated speaker works, automatically swapping to/from 3.5mm IO
- Tested with Chromium, Element should also work
Notes:
- Integrated speaker volume is a bit low
- Integrated mic does not work (possible kernel/driver issue)
- USB/BT sound devices does not work (will be done separately)

2024-04-24 08:36 UTC, leivos-unikie reviewed
Test results on Lenovo-X1-gen11

manual testing
- Poweroff and reboot buttons don't work
- All apps launch by clicking their icons
- Audio output works both from integrated speakers and 3.5mm headphones, automatically swapping to/from 3.5mm IO
- Audio output works both in chromium and element
- Integrated microphone does not work
- Youtube video real playback time does not differ from the video nominal lenght
- Increasing volume works in audio-vm with “pactl set-sink-volume @DEFAULT_SINK@ 48000”

ci-test-automation
- performance ok
- bat tests passed

2024-04-24 12:09 UTC, leivos-unikie commented
Now reboot and poweroff buttons work.

2024-04-29 08:34 UTC, leivos-unikie commented
Tested 3.5mm mobile phone headphones mic again with instructions from Jon.

- It works if plugged before chromium window is opened. 
- If headphones is plugged in when chromium window is already open the mic doesn't work. In this case closing all chromium windows and then opening a new chromium window sets mic working.

2024-04-29 08:42 UTC, leivos-unikie commented
Tested that 3.5mm headphones mic works also in Element app Jitsi Video Conference but only if plugged before pressing the button "Join Conference".

2024-04-29 09:12 UTC, leivos-unikie commented
Noticed something strange when pressing ghaf desktop poweroff button while 3.5mm headset connected and Jitsi Video Conference call active. Laptop power led did shut down but two leds stayed on:
- speakers off / F1
- mute / F4

Tried to reproduce the issue. Again the same setup. This time all leds of the laptop shutdown but I heard that fan is running. After few minutes fan stopped but the machine was still not shutdown. I could verify this by pressing the power button and nothing happening. Only after doing hard reset (pressing the power button 15 sec) I was able to boot the laptop.

Tried to reproduce with same setup except 3.5mm headset not plugged. This time laptop shut down normally.

2024-04-29 09:19 UTC, milva-unikie commented
> Noticed something strange when pressing ghaf desktop poweroff button while 3.5mm headset connected and Jitsi Video Conference call active. Laptop power led did shut down but two leds stayed on:
> 
>     * speakers off / F1
> 
>     * mute / F4
> 
> 
> Tried to reproduce the issue. Again the same setup. This time all leds of the laptop shutdown but I heard that fan is running. After few minutes fan stopped but the machine was still not shutdown. I could verify this by pressing the power button and nothing happening. Only after doing hard reset (pressing the power button 15 sec) I was able to boot the laptop.
> 
> Tried to reproduce with same setup except 3.5mm headset not plugged. This time laptop shut down normally.

I noticed this same thing and just started trying to reproduce it. I tested 3.5 mm headset with Chromium and after that shut down the laptop with poweroff button. Mentioned leds stayed on.

2024-04-29 09:42 UTC, vilvo commented
> > Noticed something strange when pressing ghaf desktop poweroff button while 3.5mm headset connected and Jitsi Video Conference call active. 
...   
> > Tried to reproduce the issue. Again the same setup. This time all leds of the laptop shutdown but I heard that fan is running. After few minutes fan stopped but the machine was still not shutdown. I could verify this by pressing the power button and nothing happening.
...
> > Tried to reproduce with same setup except 3.5mm headset not plugged. This time laptop shut down normally.
> 
> I noticed this same thing and just started trying to reproduce it. I tested 3.5 mm headset with Chromium and after that shut down the laptop with poweroff button. Mentioned leds stayed on.

#565 could be adapted to log from relevant VMs to persistent storage to capture what's going on here.

2024-04-30 06:09 UTC, leivos-unikie commented
> > > Noticed something strange when pressing ghaf desktop poweroff button while 3.5mm headset connected and Jitsi Video Conference call active.
> > > ...
> > > Tried to reproduce the issue. Again the same setup. This time all leds of the laptop shutdown but I heard that fan is running. After few minutes fan stopped but the machine was still not shutdown. I could verify this by pressing the power button and nothing happening.
> > > ...
> > > Tried to reproduce with same setup except 3.5mm headset not plugged. This time laptop shut down normally.
> > 
> > 
> > I noticed this same thing and just started trying to reproduce it. I tested 3.5 mm headset with Chromium and after that shut down the laptop with poweroff button. Mentioned leds stayed on.
> 
> #565 could be adapted to log from relevant VMs to persistent storage to capture what's going on here. See Testing-section in the #565 PR description.

I tried rebasing on that log-vm and solving few merge conflicts. But the build fails.

2024-04-30 09:08 UTC, leivos-unikie commented
Tried to see `journalctl -b-1` after shutdown with 3.5mm mic on
`No journal boot entry found from the specified boot offset (-1).`

After normal shutdown `journal -b-1` shows logs from the previous boot.

Then tried to leave this running on ghaf-host while doing the shutdown test:
`journalctl -f > /home/ghaf/host-journalctl.log &`

but there was nothing special, just repeating these:
```
Apr 30 13:00:55 ghaf-host vsockproxy[898]: Connection 6 RX 7132 bytes in 1.00 seconds, transfer rate 0.01 MB/s, rx total 185952
Apr 30 13:00:55 ghaf-host vsockproxy[898]: Connection 6 TX 29677456 bytes in 1.00 seconds, transfer rate 29.68 MB/s, tx total 353325956
Apr 30 13:00:56 ghaf-host vsockproxy[898]: Connection 5 RX 21391864 bytes in 1.00 seconds, transfer rate 21.38 MB/s, rx total 374717820
Apr 30 13:00:56 ghaf-host vsockproxy[898]: Connection 5 TX 4556 bytes in 1.00 seconds, transfer rate 0.00 MB/s, tx total 190508
Apr 30 13:00:56 ghaf-host vsockproxy[898]: Connection 6 RX 4556 bytes in 1.00 seconds, transfer rate 0.00 MB/s, rx total 190508
Apr 30 13:00:56 ghaf-host vsockproxy[898]: Connection 6 TX 21391864 bytes in 1.00 seconds, transfer rate 21.38 MB/s, tx total 374717820



```

2024-05-02 06:19 UTC, leivos-unikie commented
Tested 'shutdown with 3.5mm headset mic active' issue also with current ghaf mainline build (himalia 82). This issue is not in the mainline.

2024-05-03 12:23 UTC, josa41 commented
I was able to reproduce this with just audiovm so ssh to audiovm and record audio with pulseaudio tools 
 `parecord -r output.wav`

Now stop microvm@audio-vm.service from host and click the shutdown icon from guivm.
The audio indicator lights in most cases stay on and some cases the X1 bottom fan keeps spinning even when the lights may turn off.

2024-05-06 14:05 UTC, josa41 commented
Figured out a way to reset the audio device on host after audio-vm has shut down and audio device is got in some buggy state. This can be demoed as below:

So after ssh to audio-vm and starting a recording
`parecord -r output.wav`

ssh to host and use systemctl to shutdown audio-vm to get to error state
After the audio-vm shutdown (when audiovm is recording) turning off the laptop will result in the bottom fan and parts of the laptop staying on..

This can be fixed from host by forcing a reset on the pci device (remove device and rescan bus):
`sudo su
echo "1" /sys/bus/pci/devices/0000:00:00:1f.3/remove
sleep 1
echo "1" /sys/bus/pci/devices/0000:00:1f.0/rescan`

Next step is figure out how to automate this..

2024-05-08 10:12 UTC, Mic92 commented
So by just looking at the code, something like the following should allow to run code after the service has started:

```
systemd.services."microvm@audio-vm".serviceConfig = {
  ExecStartPost = "+${pkgs.writeShellScript "reload-audio" ''
    echo "1" /sys/bus/pci/devices/0000:00:00:1f.3/remove
    sleep 1
    echo "1" /sys/bus/pci/devices/0000:00:1f.0/rescan
  ''}";
};
```

Now the sleep command might be a bit racy. Maybe you can find some condition that you can check if the 1s was not enough and you have to retry. Another issue with the postStart is figuring out the readiness of the hypervisor. It looks like cloud-hypervisor has support for systemd-notify socket notification but I think this one is using qemu?

2024-05-08 11:51 UTC, Mic92 commented
Ok. So for context, @josa41 found out that the resets brings back the audio device power state from D3 into D0.

2024-05-08 14:22 UTC, josa41 commented
Tested sound and audio recording with chromium
- Microphone works only with 3.5mm headset
- Laptop shutdown issue fixed

2024-05-10 09:56 UTC, leivos-unikie commented
Tested first the laptop shutdown issue with 3.5mm headset mic plugged
- with chromium, ok
- element app does not detect any microphone

2024-05-10 11:36 UTC, leivos-unikie reviewed
**Test results on Lenovo-X1**
- ci-test-automation bat tests passed / performance ok
- All apps launch
- No shutdown issues
- Audio input/output works in chromium with 3.5.mm headset
- Audio input/output does not work in element app, not with 3.5mm headset nor with integrated speakers/mic

2024-05-10 13:46 UTC, josa41 commented
It seems element-vm network setup is done so that it does not resolve audio-vm.ghaf or other ghaf internal dns addresses. It does have access to ghaf addresses with direct ip address.

2024-05-14 08:20 UTC, leivos-unikie approved these changes
Rebased josa41 audiovm branch on josa41 origin/element-dns-fix with
`git rebase origin/element-dns-fix`

to be able run tests for both PRs https://github.com/tiiuae/ghaf/pull/576 and https://github.com/tiiuae/ghaf/pull/600 merged together.

Test reults on Lenovo-X1:

- Now 3.5mm headset audio input/output works in Element App
- Intergrated speakers work. 
- Integrated mic does not work. Logi USB headset does not work. (this was expected, will be fixed separately)
- All apps launch from icons
- ci-test-automation tests pass and performance test are ok

2024-05-28 10:52 UTC, brianmcgillion requested changes

2024-05-28 10:52 UTC, brianmcgillion commented on modules/microvm/virtualization/microvm/audiovm.nix
> +        nixpkgs.hostPlatform.system = configHost.nixpkgs.hostPlatform.system;
nit

nixpkgs = { 
   buildPlatform ...
   hostplatform ...
};

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/appvms/chromium.nix
> +      hardware.pulseaudio.extraConfig = ''
hardware.pulseaudio = {
enable ...
extraConfigs ...
};

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/appvms/element.nix
> +      hardware.pulseaudio.extraConfig = ''
hardware.pulseaudio = {
enable ...
extraConfigs ...
};

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/appvms/element.nix
> +
for the refactoring patch this is duplicate from the chromium vm. can be broken out to a common module.

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/audiovmExtraModules.nix
> +    services.pipewire.configPackages = [
combine into the  `services.pipewire = {` stanza above

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/audiovmExtraModules.nix
> +    microvm.kernelParams = [
combine the microvm namespaces.

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/everything.nix
>              security.polkit.extraConfig = powerControl.polkitExtraConfig;
combine security .polkit

2024-05-28 10:52 UTC, brianmcgillion commented on targets/lenovo-x1/everything.nix
> +          })
there is something wrong here as this has all been removed and refactored to linwa 42-53 above

2024-05-28 11:49 UTC, brianmcgillion approved these changes

2024-05-28 11:50 UTC, leivos-unikie commented
I ran regression test with an image built before that last force-push.

- ci-test-automation passed, performance ok
- all apps launch

Tested that integrated speakers and microphone worked with chromium, as well as 3.5mm headset audio and mic works.

2024-05-28 19:26 UTC, merged