microvm: Add initial vTPMs implementation for applications VMs
tiiuae/ghaf pull request #641
Opened 2024-05-30 06:20 UTC by humaidq-tii

Add initial vTPMs implementation for applications VMs using `swtpm`.

This doesn't include the PKCS11 interface, as that requires persistence in the guest VMs.

## Description of changes

- Automatically setup `swtpm` for VMs with vTPM enabled.
- vTPM can be enabled by setting `vtpm.enable = true;` in an app VM.
- vTPM can only be applied to app VMs, not other system or peripheral VMs.

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [x] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing

- vTPM is enabled for Chromium for now.
- SSH into Chromium VM.
- `/dev/tpm0` and `/dev/tpmrm0` should be available.
- tpm2-tools is available for additional testing.

2024-06-03 12:56 UTC, brianmcgillion approved these changes

2024-06-04 09:24 UTC, leivos-unikie approved these changes
Tested on Lenovo-X1 (boot from USB SSD)
- ci-test-automation passed, performance ok
- all apps launch

- Checked that /dev/tpm0 and /dev/tpmrm0 are available in chromium-vm
- Checked with `tmp2` that tpm2-tools are available

2024-06-04 09:58 UTC, leivos-unikie requested changes
Hold on... just noticed that there is something weird in shutdown, it takes now 35s for all the leds of the laptop to shut down but previously took less than 5s.

2024-06-04 10:19 UTC, leivos-unikie commented
After doing some more shutdown tests it seems that the poweroff time is somewhat random, measured times between 5 - 50 sec.

2024-06-04 11:02 UTC, leivos-unikie commented
It seems that problem with audio-vm caused the long shutdown issue. Extract from journalctl of 27 sec shutdown sequence

Jun 04 14:20:51 ghaf-host systemd[1]: Stopped Setup MicroVM 'gui-vm' TAP interfaces.
Jun 04 14:21:13 ghaf-host microvm@admin-vm[1095]: cloud-hypervisor: 60.081128s: <vmm> ERROR:virtio-devices/src/vhost_user/vu_common_ctrl.rs:410 -- Failed connecting the backend after trying for 1 minute: VhostUserProto>
Jun 04 14:21:13 ghaf-host kernel: virbr0: port 9(tap-admin-vm) entered disabled state
Jun 04 14:21:13 ghaf-host systemd-networkd[712]: tap-admin-vm: Lost carrier
Jun 04 14:21:13 ghaf-host microvm@admin-vm[1095]: Error booting VM: VmBoot(DeviceManager(CreateVirtioFs(VhostUserConnect)))
Jun 04 14:21:13 ghaf-host systemd[1]: microvm@admin-vm.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 14:21:13 ghaf-host systemd[1]: microvm@admin-vm.service: Failed with result 'exit-code'.
Jun 04 14:21:13 ghaf-host systemd[1]: Stopped MicroVM 'admin-vm'.

Tested shutdown with ghaf mainline. Long shutdown is not happening there and journalctl shows that admin-vm stops decently. I suppose this PR (merged 2 hours ago) fixes the problem: https://github.com/tiiuae/ghaf/pull/643

2024-06-04 11:24 UTC, leivos-unikie commented
> > audio-vm caused the long shutdown issue.
> 
> I also noticed long shutdown, but since this PR doesn't change `audio-vm` I think it is fine. Though `chromium-vm` will send a TPM Shutdown command on poweroff, but this shouldn't add any noticeable delay.

I agree. 

The problem was in admin-vm, I had a typo.

I think shutting down chromium-vm first didn't actually cause shorter shutdown time, there was some random variation and faster shutdown happened just on that run.

2024-06-04 14:17 UTC, merged