Enable AppArmor
tiiuae/ghaf pull request #714
Opened 2024-08-06 08:18 UTC by gangaram-tii

## Description of changes
- Enabled AppArmor 
- AppArmor profiles for Chromium and Firefox
- AppArmor enabled in chromium-vm along with Chromium profile

## Checklist for things done

- [x] Summary of the proposed changes in the PR description
- [x] More detailed description in the commit message(s)
- [x] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [x] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [] Author has run `nix flake check --accept-flake-config` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status

## Testing
Verify if chromium profile is active inside chromium-vm.
`$> sudo aa-status`

Do audio and video recording/playback, Google spread sheet editing using Chromium browser.

A brief documentation and test report are available in confluence.

https://ssrc.atlassian.net/wiki/spaces/GA/pages/1187708968/Security#1.-AppArmor%3A

2024-08-06 10:03 UTC, brianmcgillion requested changes
The Chrome settings should also be applied to the business VM where it is also running Chrome.

2024-08-06 11:10 UTC, mbssrc commented
Hey, many thanks for the PR. 

It would be great to add the following information to the documentation:
- Profile creation: Base profile(s) used, adjustments and reasoning
- Test information: How did we verify the profiles functionally, and what security testing/analysis did we perform?
  E.g., do we have a list of recent chromium CVEs and a potential analysis of how the confinement measures may have mitigated the impact? This would be a great motivation for using the profiles. 
- Performance impact: Thanks for the figures provided. It's however not entirely clear to me how we ended up with the conclusion.
  Can we add a final table with the testing results, with clear indicator of performance impact of the test case such as "video streaming: ~5-10% overhead during initial load, ~1% during execution, etc." 
  Also, it would be helpful to describe the test methodology and tools used, so one can verify the results.

2024-08-06 11:11 UTC, mbssrc requested changes
Hey, many thanks for the PR. 

It would be great to add the following information to the documentation:
- Profile creation: Base profile(s) used, adjustments and reasoning
- Test information: How did we verify the profiles functionally, and what security testing/analysis did we perform?
  E.g., do we have a list of recent chromium CVEs and a potential analysis of how the confinement measures may have mitigated the impact? This would be a great motivation for using the profiles. 
- Performance impact: Thanks for the figures provided. It's however not entirely clear to me how we ended up with the conclusion.
  Can we add a final table with the testing results, with clear indicator of performance impact of the test case such as "video streaming: ~5-10% overhead during initial load, ~1% during execution, etc." 
  Also, it would be helpful to describe the test methodology and tools used, so one can verify the results.

2024-08-15 21:13 UTC, gangaram-tii commented
> The Chrome settings should also be applied to the business VM where it is also running Chrome.

Done.

2024-08-15 21:20 UTC, gangaram-tii commented
Rebased to latest main.

2024-08-15 21:25 UTC, gangaram-tii commented on modules/common/security/apparmor/profiles/chromium.nix
As of now profiles in the abstractions/ and tunables/ directories are available on NixOS. 

https://discourse.nixos.org/t/apparmor-default-profiles/16780

2024-08-15 21:36 UTC, gangaram-tii commented
> Hey, many thanks for the PR.
> 
> It would be great to add the following information to the documentation:
> 
>     * Profile creation: Base profile(s) used, adjustments and reasoning
>>>>>> Updated the [page](https://ssrc.atlassian.net/wiki/spaces/GA/pages/1271595056/Mandatory+Access+Control+MAC+AppArmor#2.-Profile%3A) on Confluence.

  
>     * Test information: How did we verify the profiles functionally, and what security testing/analysis did we perform?
>       E.g., do we have a list of recent chromium CVEs and a potential analysis of how the confinement measures may have mitigated the impact? This would be a great motivation for using the profiles.
>
>>>>>> We did testing to verify if the rules in profile are behaving as per our expectation. Security analysis report is available [here](https://ssrc.atlassian.net/wiki/spaces/GA/pages/1271595056/Mandatory+Access+Control+MAC+AppArmor#3.-Security-Analysis%3A).
 
>     * Performance impact: Thanks for the figures provided. It's however not entirely clear to me how we ended up with the conclusion.
>       Can we add a final table with the testing results, with clear indicator of performance impact of the test case such as "video streaming: ~5-10% overhead during initial load, ~1% during execution, etc."
>       Also, it would be helpful to describe the test methodology and tools used, so one can verify the results.
>>>>> Updated the test report and created a [conclusion table](https://ssrc.atlassian.net/wiki/spaces/GA/pages/1271595056/Mandatory+Access+Control+MAC+AppArmor#4.2.2--Conclusion).
>>>>> Will upload scripts I used to take performance data.

2024-09-18 11:54 UTC, Mic92 commented
Upstream fixes has been merged.

2024-10-01 09:27 UTC, mbssrc approved these changes

2024-10-18 10:06 UTC, UnikieHR commented
![image](https://github.com/user-attachments/assets/b7470130-0173-4272-8250-77b135f076c8)

2024-10-24 03:22 UTC, barnabakos commented
2 commits up to: b07c0cf6fc83a844fc78e3e101c7aecb467f38b9
rebased to current tip of Ghaf main without conflicts: 5d5ae6d5fcee689c6ca31488cc6ed054221eadfe

platform: **Lenovo X1 Carbon; flash script; USB SSD**
- ci-test-automation suite: ok
- starting apps: ok
- regression / ad-hoc testing: ok

#### works:
- AppArmor profile is active inside chromium-vm & business-vm
- audio and video recording/playback

#### notes:
- N/A

#### issues:
- cannot save files to "Unsafe share" from Chromium and Trusted Browser
![unsafe_share](https://github.com/user-attachments/assets/7a538ff7-385d-4a4d-a154-23fc8b09eb8b)

2024-11-06 13:44 UTC, gangaram-tii commented
Added rule to give read write access to this directory. Retest please.

2024-11-09 17:17 UTC, barnabakos commented
2 commits up to: bffa1dcafe7451259e89c848eed8998afe21c6de
rebased to current tip of Ghaf main without conflicts: 76852b945ac148782f0e78c128e2691e25c80d2d

platform: **Lenovo X1 Carbon; flash script; USB SSD**
- ci-test-automation suite: ok
- starting apps: ok
- regression / ad-hoc testing: ok

#### works:
- AppArmor profile is active inside chromium-vm & business-vm
- audio and video recording/playback
- chrome-vm logs are sent to Grafana
- MS apps are working in Trusted Browser
- comms-vm apps are working

#### notes:
- N/A

#### issues:
- same error message appears, but can save after dismissing the window
- "Open page in normal browser" doesn't work from Trusted Browser
- pdf files open in browser by default; should open in Zathura
- call & video call from/to teams worked only once; cannot establish a call anymore after that;
  not even after reboot

2024-11-29 11:13 UTC, gangaram-tii commented
@barnabakos Please retest this PR.

2024-11-30 16:39 UTC, barnabakos commented
3 commits up to: 1a63ca75fcd89a1df253d0e57e225da887c8503b
commit is on top of latest tip of Ghaf main: da685e3e4827cd17848e4925f8b1e4311b31f993

platform: **Lenovo X1 Carbon; flash script; USB SSD**
- ci-test-automation suite: ok
- starting apps: ok
- regression / ad-hoc testing: ok

#### works:
- AppArmor profile is active inside chromium-vm & business-vm
- audio and video recording/playback
- files can be saved to "Unsafe share" from Chromium and Trusted Browser

#### notes:
- N/A

#### issues:
- N/A

2024-12-05 07:35 UTC, mbssrc approved these changes

2024-12-05 07:37 UTC, vunnyso approved these changes

2024-12-11 06:13 UTC, brianmcgillion approved these changes

2024-12-11 07:13 UTC, merged