Add printing service in chromium-vm and bussiness-vm
tiiuae/ghaf pull request #783
Opened 2024-09-11 12:21 UTC by Nerox9

## Description of changes

CUPS and Avahi sercvie are enabled in chromium-vm and bussines-vm.
Avahi service reflection is added into net-vm.

## Checklist for things done

- [ ] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [ ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [ ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `make-checks` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [ ] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

- [ ] List all targets that this applies to:
- [ ] Is this a new feature
  - [ ] List the test steps to verify:
- [ ] If it is an improvement how does it impact existing functionality?

2024-09-13 07:27 UTC, vadika commented
Let's merge!

2024-09-13 08:42 UTC, humaidq-tii requested changes

2024-09-16 14:32 UTC, Nerox9 commented on overlays/custom-packages/cups/default.nix
> +# SPDX-License-Identifier: Apache-2.0
It is because of [this bug](https://github.com/OpenPrinting/cups/issues/998)
A comment is added.

2024-09-16 14:32 UTC, Nerox9 commented on overlays/custom-packages/cups/default.nix
> +    version = "17.5.229";
It was a residue of a copy-paste and removed.

2024-09-19 10:21 UTC, emrahbillur commented
I tested this PR with all builds of nvidia-agx and nvidia-nx (both cross compile and remote builder) and succeeded in the builds where our system that tests our PRs seem to have a problem of building.

2024-09-19 10:56 UTC, milva-unikie commented
**Tested on Lenovo-X1**(`nixos-rebuild switch`)

I tested with HP Laserjet M15w and with Canon ir-adv c3822.

Issues:
- Printing pdf files does not work in most cases.
	- When you try to open a pdf "normally", it is automatically downloaded and after that opens in Zathura. In Zathura there is a printing menu (ctrl+P), but the printer can not be found from there.
	- Some pages offer an option to go around that with preview options, but
	  - in OneDrive Open -> Open in browser -> 3 dots -> Print -> downloads the file.
	  - in Teams Click the file -> only an option to download, no way to print.
	  - in Gmail Click the file -> Print ->  downloads the file.
	  - in Outlook Preview -> Print -> Printing menu opens, so in Outlook this actually does work.
     - Printing from Excel & Powerpoint does not work, because they export the files first to pdf -> downloads -> open in Zathura with no option to print.
- Printer needs to be added again after every restart. Would it be possible to store the configuration in storage?
- Bookmark to "CUPS" was added to Chromium and Trusted browser. Could that be renamed to "Printing" or something like that? (The bookmarks did not show up with `nixos-rebuild switch` but @johannarautanen confirmed that in a flashed image they are there)
- In Chromium and Trusted browser ctrl+P -> Destination -> See more... -> Manage does not open anything.

Working:
- Printer can be added.
  - HP Laserjet  was detected automatically, Canon needed to be added manually.
  - Adding needs to be done in both Chromium and Trusted browser separately. I assume this is intended behavior?
- Printing a webpage with ctrl+P works.
- Printing from Word works.

Note: I did not run the automated tests yet. This pr will need to be retested after printing pdf files has been solved.

2024-09-20 14:32 UTC, Nerox9 commented
> **Tested on Lenovo-X1**(`nixos-rebuild switch`)
> 
> I tested with HP Laserjet M15w and with Canon ir-adv c3822.
> 
> Issues:
> 
>     * Printing pdf files does not work in most cases.
>       
>       * When you try to open a pdf "normally", it is automatically downloaded and after that opens in Zathura. In Zathura there is a printing menu (ctrl+P), but the printer can not be found from there.
>       * Some pages offer an option to go around that with preview options, but
>         
>         * in OneDrive Open -> Open in browser -> 3 dots -> Print -> downloads the file.
>         * in Teams Click the file -> only an option to download, no way to print.
>         * in Gmail Click the file -> Print ->  downloads the file.
>         * in Outlook Preview -> Print -> Printing menu opens, so in Outlook this actually does work.
>       * Printing from Excel & Powerpoint does not work, because they export the files first to pdf -> downloads -> open in Zathura with no option to print.
> 
>     * Printer needs to be added again after every restart. Would it be possible to store the configuration in storage?
> 
>     * Bookmark to "CUPS" was added to Chromium and Trusted browser. Could that be renamed to "Printing" or something like that? (The bookmarks did not show up with `nixos-rebuild switch` but @johannarautanen confirmed that in a flashed image they are there)
> 
>     * In Chromium and Trusted browser ctrl+P -> Destination -> See more... -> Manage does not open anything.
> 
> 
> Working:
> 
>     * Printer can be added.
>       
>       * HP Laserjet  was detected automatically, Canon needed to be added manually.
>       * Adding needs to be done in both Chromium and Trusted browser separately. I assume this is intended behavior?
> 
>     * Printing a webpage with ctrl+P works.
> 
>     * Printing from Word works.
> 
> 
> Note: I did not run the automated tests yet. This pr will need to be retested after printing pdf files has been solved.

I added CUPS into Zathura VM too to solve the issue quickly. It can only be used with driverless printers detected automatically but it will be solved in the future with unified printing service.

Storage VM configurations added.

Manage button redirects to distro settings and we don't have a settings UI yet as far I know. I checked quickly how to manage the button but I don't have a solution yet.

2024-09-25 09:52 UTC, milva-unikie commented
> I added CUPS into Zathura VM too to solve the issue quickly. It can only be used with driverless printers detected automatically but it will be solved in the future with unified printing service.
> 
> Storage VM configurations added.
> 
> Manage button redirects to distro settings and we don't have a settings UI yet as far I know. I checked quickly how to manage the button but I don't have a solution yet.
> 
> @milva-unikie

Printing with office printers in Finland & UAE has been confirmed to be working from browser (thanks @jkuro-tii)

Driverless printing does not work in the offices sadly, so there will need to be another solution for that.

The manage button is probably not that important. If there is no easy solution, I think it is fine to leave it as it is.

Printer information is now saved between boots. Thanks also for changing the bookmark name to "Printing".

2024-10-18 10:05 UTC, UnikieHR commented
![image](https://github.com/user-attachments/assets/bb53d50e-25b0-4a2a-a14b-a3c252f3e2f1)

2026-04-25 09:42 UTC, closed without merging