Refactor Office 365 firewall setup for BusinessVM
tiiuae/ghaf pull request #800
Opened 2024-09-24 08:31 UTC by vadika

Office365 firewalling refactored to use Microsoft-provided PAC data to ease firewall passthrough and automate  application of future changes in this data.

## Description of changes

## Checklist for things done

- [ ] Summary of the proposed changes in the PR description
- [ ] More detailed description in the commit message(s)
- [ ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [ ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [ ] PR linked to architecture documentation and requirement(s) (ticket id)
- [ ] Test procedure described (or includes tests). Select one or more:
  - [ ] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `make-checks` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [ ] Author has added reviewers and removed PR draft status
- [ ] Change requires full re-installation
- [ ] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

- [ ] List all targets that this applies to:
- [ ] Is this a new feature
  - [ ] List the test steps to verify:
- [ ] If it is an improvement how does it impact existing functionality?

2024-09-24 09:51 UTC, milva-unikie commented
I can open youtube.com (and many other pages) in Trusted browser. Firewall seems to be not working at all.

2024-09-24 11:33 UTC, milva-unikie commented
I can still open Youtube in Trusted browser.

2024-09-25 05:55 UTC, milva-unikie commented
And now everything is blocked. Even Teams and Outlook do not work.

2024-09-26 06:29 UTC, enesoztrk requested changes

2024-09-26 06:29 UTC, enesoztrk commented on modules/reference/appvms/business.nix
> +                echo "ip6tables -I INPUT -d $ip -j ACCEPT"
we need to check the source IP for input. `ip6tables -I INPUT -s $ip -j ACCEPT`

2024-09-26 06:29 UTC, enesoztrk commented on modules/reference/appvms/business.nix
> +                echo "iptables -I INPUT -d $ip -j ACCEPT"
we need to check the source IP for input. `iptables -I INPUT -s $ip -j ACCEPT`

2024-09-26 06:29 UTC, enesoztrk commented on modules/reference/appvms/business.nix
> +                echo "iptables -I OUTPUT -p tcp --dport 443 -m string --string \"$processed_url\" --algo bm -j ACCEPT"
Most of the websites use HTTPS, which means that the payloads are encrypted. This method does not work.

2024-09-26 06:29 UTC, enesoztrk commented on modules/reference/appvms/business.nix
> +                echo "iptables -I INPUT -p tcp --dport 443 -m string --string \"$processed_url\" --algo bm -j ACCEPT"
Same as previous comment. In addition, `--sport` should have been used rather than `--dport`.

2024-10-02 07:54 UTC, vadika commented
Dropping this PR in favor ot https://github.com/tiiuae/ghaf/pull/811

2024-10-02 07:54 UTC, closed without merging