Added shared memory multi-server feature
tiiuae/ghaf pull request #917
Opened 2024-11-28 07:53 UTC by jkuro-tii

## Description of changes

The memsocket application has been enhanced with the following new features and updates:

    Host Support:
        The application can now run on the host in addition to virtual machines (VMs).

    Multi-Server Capability:
        Multiple memsocket instances operating in server mode are now supported.
        Each server instance is configured with a list of specific client IDs it serves.
        Multiple servers can run simultaneously on a single VM or the host.

    Client ID Exclusivity:
        Each client ID must be managed by only one server across the entire system.

    Configuration Updates:
        Renamed some Nix configuration options for clarity.

    Option Changes:
        The -c and -s options have been swapped:
            -c: Now used for running in server mode.
            -s: Now used for running in client mode.
        A new -l option has been introduced for server mode to specify the list of client IDs to be serviced.   
        A new -h option has been introduced for indicating run on the host

Documentation: https://confluence.tii.ae/x/uEPOAg

## Checklist for things done

- [ X] Summary of the proposed changes in the PR description
- [ X] More detailed description in the commit message(s)
- [ X] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [X] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ ] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [X] PR linked to architecture documentation and requirement(s) (ticket id)
- [x] Test procedure described (or includes tests). Select one or more:
  - [x] Tested on Lenovo X1 `x86_64`
  - [ ] Tested on Jetson Orin NX or AGX `aarch64`
  - [ ] Tested on Polarfire `riscv64`
- [ ] Author has run `make-checks` and it passes
- [ ] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
- [X] Author has added reviewers and removed PR draft status
- [X] Change requires full re-installation
- [ ] Change can be updated with `nixos-rebuild ... switch`

## Instructions for Testing

- [ ] List all targets that this applies to:
- [ ] Is this a new feature
  - [ ] List the test steps to verify:
- [ ] If it is an improvement how does it impact existing functionality?

2024-11-28 12:36 UTC, josa41 commented
Nothing too obvious to comment in the code.
I did test this also with pulseaudio and got everything to work just fine.
During my testing i found two issues.
1. If the application socket (pulseaudio in my tests) is not available when memsocket starts then data does not reach the socket. Restarting memsocket helps for this or adding a delay for memsocket to start after the application.
2. Memsocket/kernel crashes when a second memsocket server is started from command line on the same VM with another id

I passed more details to Jarek in slack

2024-12-04 12:38 UTC, mbssrc commented
Any idea how this can or should be tested?

2025-01-09 11:58 UTC, josa41 approved these changes

2025-01-09 11:59 UTC, josa41 commented
Tested briefly and audio works through shared mem.
Had some trouble with permissions but that is not related to this change.

2025-01-14 11:47 UTC, leivos-unikie commented
Tested again on Lenovo-X1

The bug is fixed.

bat tests pass

Monitored now all VMs with the test script while starting all apps and closing them. Number of file descriptors change as noticed before. Nothing suspicious there.

2025-01-15 07:10 UTC, johannarautanen commented
**Checked with native Orin AGX and NX**

- build can be done
- Ghaf booted up
- applications launched
- automation test cases were ok

Notes:
- so far the build size flashed to the memory stick has been about 7-8GB, with this PR the size is 11-12 GB

2025-01-15 07:11 UTC, johannarautanen commented
**Checked with crosscompile Orin AGX and NX**'

Issues:
- cannot create the build fro AGX or NX

2025-01-15 07:25 UTC, jkuro-tii commented
It seems cross compiling for ARM is broken. For some reasons during building for the ARM platform, the `/arch/x86/` directory is accessed. 

```
 Running phase: buildPhase
build flags: SHELL=/nix/store/0irlcqx2n3qm6b1pc9rsd2i8qpvcccaj-bash-5.2p37/bin/bash KDIR=/nix/store/ffc1c388l2dv6asbpkh5v1l7nr27hchc-linux-aarch64-unknown-linux-gnu-6.6.62-dev/lib/modules/6.6.62/build MODULEDIR=\$\(out\)/lib/modules/6.6.62/kernel/drivers/char CFLAGS_kvm_ivshmem.o=\"-DCONFIG_KVM_IVSHMEM_SHM_SLOTS=10\"
cp ../drivers/char/ivshmem/kvm_ivshmem.c .
cp ../drivers/char/ivshmem/kvm_ivshmem.h .
make -C /nix/store/ffc1c388l2dv6asbpkh5v1l7nr27hchc-linux-aarch64-unknown-linux-gnu-6.6.62-dev/lib/modules/6.6.62/build M=/build/source/module modules
make[1]: Entering directory '/nix/store/ffc1c388l2dv6asbpkh5v1l7nr27hchc-linux-aarch64-unknown-linux-gnu-6.6.62-dev/lib/modules/6.6.62/build'
/nix/store/ffc1c388l2dv6asbpkh5v1l7nr27hchc-linux-aarch64-unknown-linux-gnu-6.6.62-dev/lib/modules/6.6.62/source/Makefile:768: /nix/store/ffc1c388l2dv6asbpkh5v1l7nr27hchc-linux-aarch64-unknown-linux-gnu-6.6.62-dev/lib/modules/6.6.62/source/arch/x86/Makefile: No such file or directory

```

2025-01-15 08:59 UTC, josa41 approved these changes

2025-01-15 10:54 UTC, leivos-unikie commented
I was testing https://github.com/tiiuae/ci-test-automation/pull/207 with this ghaf image and noticed that audio test fails on Lenovo-X1. Tried youtube and it does not output any sound. Ghaf Audio Control does not show any stream while running youtube video.

2025-01-15 12:43 UTC, leivos-unikie commented
> I was testing [tiiuae/ci-test-automation#207](https://github.com/tiiuae/ci-test-automation/pull/207) with this ghaf image and noticed that audio test fails on Lenovo-X1. Tried youtube in chrome, it does not output any sound. Ghaf Audio Control does not show any stream while running youtube video.

The problem seems to be in test automation not being able to use pulseaudio. That failing automated audio test rendered ghaf audio once dysfunctional but after reboot I was not able to reproduce that state.

2025-01-16 09:19 UTC, josa41 commented
> > I was testing [tiiuae/ci-test-automation#207](https://github.com/tiiuae/ci-test-automation/pull/207) with this ghaf image and noticed that audio test fails on Lenovo-X1. Tried youtube in chrome, it does not output any sound. Ghaf Audio Control does not show any stream while running youtube video.
> 
> The problem seems to be in test automation not being able to use pulseaudio. That failing automated audio test rendered ghaf audio once dysfunctional but after reboot I was not able to reproduce that state.

What do you do in the automated tests? If you use
`export PULSE_SERVER=tcp:audio-vm`
it does not work when audio through shm is enabled as whole pulseaudio communication goes through shm.
You can use:
`export PULSE_SERVER=unix:/run/memsocket/audio-client.sock`
instead. The export should be automatically added to user shells but maybe this needs some tweaking for autotest environments.

2025-01-16 10:22 UTC, leivos-unikie commented
> > > I was testing [tiiuae/ci-test-automation#207](https://github.com/tiiuae/ci-test-automation/pull/207) with this ghaf image and noticed that audio test fails on Lenovo-X1. Tried youtube in chrome, it does not output any sound. Ghaf Audio Control does not show any stream while running youtube video.
> > 
> > 
> > The problem seems to be in test automation not being able to use pulseaudio. That failing automated audio test rendered ghaf audio once dysfunctional but after reboot I was not able to reproduce that state.
> 
> What do you do in the automated tests? If you use `export PULSE_SERVER=tcp:audio-vm` it does not work when audio through shm is enabled as whole pulseaudio communication goes through shm. You can use: `export PULSE_SERVER=unix:/run/memsocket/audio-client.sock` instead. The export should be automatically added to user shells but maybe this needs some tweaking for autotest environments.

Thanks Jon. I will try with that.

Anyway this problem with ci-test-automation is not a bug in ghaf. Just need to adapt test automation to the change. And the audio tests were not even yet integrated to the regular test runs. I remove the x1 bug tag.

2025-01-17 11:03 UTC, leivos-unikie commented
> > > > I was testing [tiiuae/ci-test-automation#207](https://github.com/tiiuae/ci-test-automation/pull/207) with this ghaf image and noticed that audio test fails on Lenovo-X1. Tried youtube in chrome, it does not output any sound. Ghaf Audio Control does not show any stream while running youtube video.
> > > 
> > > 
> > > The problem seems to be in test automation not being able to use pulseaudio. That failing automated audio test rendered ghaf audio once dysfunctional but after reboot I was not able to reproduce that state.
> > 
> > 
> > What do you do in the automated tests? If you use `export PULSE_SERVER=tcp:audio-vm` it does not work when audio through shm is enabled as whole pulseaudio communication goes through shm. You can use: `export PULSE_SERVER=unix:/run/memsocket/audio-client.sock` instead. The export should be automatically added to user shells but maybe this needs some tweaking for autotest environments.
> 
> Thanks Jon. I will try with that.
> 
> Anyway this problem with ci-test-automation is not a bug in ghaf. Just need to adapt test automation to the change. And the audio tests were not even yet integrated to the regular test runs. I remove the x1 bug tag.

Turned out that I was able to run automated audio tests when I added sudo to the commands but it works only once if the test setup does log in (before the tests) and log out (afterwards). Tested also manually that I can run the pulseaudio commands with sudo as long as I don't do Log out and Log in.  

If doing log in, log out and log in after boot, I get this (which would still work after first login):
[ghaf@chrome-vm:/tmp]$ sudo pactl list sources
[sudo] password for ghaf: 
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

Clearly Log out / Log in changes something in the audio compared to the first login after boot.

2025-01-17 12:47 UTC, jkuro-tii commented
I noticed that behavior on my site. I'm working on that.

2025-01-20 12:02 UTC, josa41 commented
With audio its good to check audio control application if there are new streams when you open an app. This would tell if the app is able to connect to audiovm. At least slack is run on chrome browser. Also the configuration is exactly the same as with chrome vm so in a way it should be the same. The slight difference is that the vms are started in "random" order which could make slight difference although it should not matter (shm can handle that).

2025-01-21 05:33 UTC, jkuro-tii commented
I pushed a new version, which fixes problems when logging out and in.

2025-01-22 08:14 UTC, jkuro-tii commented
I pushed the version which uses shared memory only for sending video. Shared memory audio is temporarily disabled in order to figure out proper audio config data.

2025-01-22 13:22 UTC, vadika approved these changes

2025-01-23 12:28 UTC, leivos-unikie commented
I tested on x1 that all dekstop / app launcher gui buttons work.

Got once ghaf chrashing at login screen. After reboot I didn't have any audio devices working although previously they were working.

2025-01-23 12:28 UTC, leivos-unikie commented
But after another reboot the audio devices are back.

2025-01-23 12:32 UTC, jkuro-tii commented
It the last push I turned off sending audio through shared memory. So audio issues are unlikely related with this PR.

2025-01-24 06:44 UTC, leivos-unikie commented
> It the last push I turned off sending audio through shared memory. So audio issues are unlikely related with this PR.

Yes, I agree. 

Now when thinking what happened I believe that connecting to home wifi network with the same IP space than within ghaf virtual network might have caused the crash and also temporary loss of audio.

2025-01-26 14:50 UTC, vadika approved these changes

2025-01-27 06:36 UTC, jkuro-tii commented
Created [issue](https://github.com/tiiuae/ghaf/issues/973) regarding the problem with cross-building for the ARM64 platform.

2025-01-27 13:27 UTC, josa41 approved these changes

2025-01-27 14:45 UTC, vadika approved these changes

2025-01-28 08:33 UTC, vadika approved these changes

2025-01-31 12:52 UTC, josa41 approved these changes

2025-02-25 12:18 UTC, jkuro-tii commented
I added some fixes which allow using shared memory for gui only for Lenovo X11 platform. Problems with too big image, and to much memory consumption during building no longer exist.

Please review.

2025-02-27 06:33 UTC, johannarautanen commented
**Checked with crosscompile Orin AGX and NX**
Working:
- builds can be done
- Ghaf booted up and ghaf-screen visible on the external display
- applications launched
- automation test cases were ok
- build size was for NX about 7.9 and AGX 8.3GB when flashed to the USB memory stick

2025-02-27 06:40 UTC, leivos-unikie commented
That old bug "VM apps (running outside gui.vm) don't launch after log out and log in" is back again although it was fixed at some point. (See comments on Jan 13 - 14.)

2025-02-27 08:13 UTC, johannarautanen commented
**Checked with native Orin AGX and NX**
Working:

- builds can be done
- Ghaf booted up and ghaf-screen visible on the external display
- applications launched
- automation test cases were ok

2025-02-28 08:07 UTC, vadika requested changes

2025-02-28 08:07 UTC, vadika commented on modules/reference/personalize/authorizedSshKeys.nix
> +    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwGPH/oOrD1g15uiPV4gBKGk7f8ZBSyMEaptKOVs3NG jaroslawkurowski@TII-JaroslawKurowski"
Lets move it to separate commit?

2025-02-28 08:09 UTC, jkuro-tii commented on modules/reference/personalize/authorizedSshKeys.nix
> +    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwGPH/oOrD1g15uiPV4gBKGk7f8ZBSyMEaptKOVs3NG jaroslawkurowski@TII-JaroslawKurowski"
OK

2025-02-28 08:16 UTC, jkuro-tii commented
> That old bug "VM apps (running outside gui.vm) don't launch after log out and log in" is back again although it was fixed at some point. (See comments on Jan 13 - 14.)

The bug is related to the [PR](https://github.com/tiiuae/ghaf/issues/1036) I have raised. Even after fixing the issue by removing Waypipe tmp files, quickly logging out and back in still blocks services. I can provide a temporary workaround, but I believe fixing the root cause in the mentioned PR is the better approach

2025-03-03 06:53 UTC, jkuro-tii commented
Added removal waypipe of /tmp sockets in order to fix problem with re-logging (though the [problem with quick re-logging](https://github.com/tiiuae/ghaf/issues/1036) still persists).
Removed adding public ssh key.

2025-03-03 12:52 UTC, vadika approved these changes

2025-03-06 07:51 UTC, jkuro-tii commented
Fixed the logout process. A recent [update](https://github.com/tiiuae/ghaf/issues/1036) on the main branch caused a SIGKILL signal to be sent, preventing the proper propagation of the termination event

2025-03-08 09:16 UTC, brianmcgillion requested changes

2025-03-08 09:16 UTC, brianmcgillion commented on modules/hardware/common/shared-mem.nix
> +              "business-vm"
this should be set in the modules/reference/profiles/mvp. because it it not known here in common that these are the enabled vms.

2025-03-08 09:16 UTC, brianmcgillion commented on modules/hardware/common/shared-mem.nix
> +              "gala-vm"
same as above

2025-03-08 09:16 UTC, brianmcgillion commented on modules/hardware/common/shared-mem.nix
> +          (pkgs.callPackage ../../../packages/pkgs-by-name/memsocket/package.nix { inherit (cfg) shmSlots; })
do not do this. use the  `(pkgs.memsocket.override { vms = cfg.shmSlotst; })` method to use the package

2025-03-11 09:24 UTC, jkuro-tii commented on modules/hardware/common/shared-mem.nix
> +          (pkgs.callPackage ../../../packages/pkgs-by-name/memsocket/package.nix { inherit (cfg) shmSlots; })
Done.

2025-06-03 12:32 UTC, milva-unikie commented
The issue with VMs not being active on Dell-7330 has been fixed.

Pre-merge pipeline has some failing builds and tests, but those might not be related to this PR. I will restart that run after it has finished.

2025-06-09 10:23 UTC, milva-unikie commented
Please complete the 'Instructions for Testing' section, preferably using the new PR template.

```
## Testing Instructions

### Applicable Targets
- [ ] Orin AGX `aarch64`
- [ ] Orin NX `aarch64`
- [ ] Lenovo X1 `x86_64`
- [ ] Dell Latitude `x86_64`

### Installation Method
- [ ] Requires full re-installation
- [ ] Can be updated with `nixos-rebuild ... switch`
- [ ] Other: 

### Test Steps To Verify:
<!--
Provide clear, simple step-by-step instructions to verify the functionality.
Please do not assume that readers know everything you currently know.
-->
1. ...

```

2025-06-13 06:26 UTC, jkuro-tii commented
Done.

> Please complete the 'Instructions for Testing' section, preferably using the new PR template.
> 
> ```
> ## Testing Instructions
> 
> ### Applicable Targets
> - [ ] Orin AGX `aarch64`
> - [ ] Orin NX `aarch64`
> - [ ] Lenovo X1 `x86_64`
> - [ ] Dell Latitude `x86_64`
> 
> ### Installation Method
> - [ ] Requires full re-installation
> - [ ] Can be updated with `nixos-rebuild ... switch`
> - [ ] Other: 
> 
> ### Test Steps To Verify:
> <!--
> Provide clear, simple step-by-step instructions to verify the functionality.
> Please do not assume that readers know everything you currently know.
> -->
> 1. ...
> ```

Done.

2025-06-13 10:46 UTC, milva-unikie commented
**Tested on Lenovo-X1** (`nixos-rebuild switch`)

Rebased to the latest main 9c33f5e

- Apps are displayed properly
- Apps work even after repeatedly closing and opening them
- Audio & cameras work
- Test-automation passes

2025-06-24 07:54 UTC, mbssrc approved these changes
Suggest we merge this, and do some cleanups of the interface later

2026-04-24 05:52 UTC, closed without merging